### PR TITLE
Support double in shaders when OpenGL < 4.0

### PR DESCRIPTION
**Pull request by ConnorDY**
Resolves the following error:
```
controllers.worldRenderer.shaders.ShaderException: 0(33) : error C7532: global type double requires "#version 400" or later
0(33) : error C0000: ... or #extension GL_ARB_gpu_shader_fp64 : enable

        at controllers.worldRenderer.shaders.Shader.compile(Shader.kt:54)
        at controllers.worldRenderer.Renderer.initProgram(Renderer.kt:651)
        at controllers.worldRenderer.Renderer.init(Renderer.kt:287)
        at controllers.worldRenderer.Renderer$initCanvas$glCanvas$1.initGL(Renderer.kt:173)
        at org.lwjgl.opengl.awt.AWTGLCanvas.render(AWTGLCanvas.java:123)
        at controllers.worldRenderer.helpers.Animator$HiResTimerRunnable.callRender(Animator.kt:87)
        at controllers.worldRenderer.helpers.Animator$HiResTimerRunnable.run(Animator.kt:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### CODE REVIEW

**Comment by LengaJenga** [comment]
Works on Windows 10

**Comment by ConnorDY** [comment]
@ScoreUnder I think we will want to merge this PR regardless (to make this program work on OpenGL < `4.0`), but I'd also like to figure out why our application is choosing to use older OpenGL versions in some cases.

For example, my system appears to support up to OpenGL `4.6`:
```
[connor@theseus ~]$ glxinfo | grep "OpenGL"
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 515.65.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 515.65.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 515.65.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Review by ScoreUnder — CHANGES_REQUESTED** [review]
Rather than enabling the ARB extension, we should probably be using single-precision floats

**Comment by ConnorDY** [comment]
> Rather than enabling the ARB extension, we should probably be using single-precision floats

Good idea! Let's keep this PR around for historical reasons and open a new one for that.
